name: Build Deploy Simple Web Server

on:
  push:

jobs:
  demo-jay:
    runs-on: ubuntu-latest
    
    steps:
    - name: 'Bonus Validation'
      run: 'echo Random Jay Assignment 3'
      
  jay-build-and-deploy:
    runs-on: ubuntu-latest
    steps:
    - uses: 'actions/checkout@v3'
    - id: 'auth'
      name: 'Authenticate to Google Cloud'
      uses: 'google-github-actions/auth@v0'
      with:
        credentials_json: '${{ secrets.GCP_CREDENTIALS }}'
       
    - name: 'Set up Cloud SDK'
      uses: 'google-github-actions/setup-gcloud@v0'
      
    - name: 'Submit to cloud build'
      run: gcloud builds submit --tag gcr.io/verdant-cable-284710/simple-webserver
      
    - name: 'Deploy to Cloud Run'
      run: gcloud run deploy simple-webserver --image=gcr.io/verdant-cable-284710/simple-webserver:latest --region=us-central1 --allow-unauthenticated --service-account=githubexample@verdant-cable-284710.iam.gserviceaccount.com

